### ISSUE TITLE
Custom international keys

### ISSUE THREAD

**Issue by JavierOrtegaP** [sunaku/glove80-keymaps#1]
Hi,

Can you please explain how to include Ñ in any layer while on en-US? Would like it on right pinky for magic layer and can't get it to work.  

Thanks!

**Comment by sunaku** [comment]
That would depend on your operating system: see [this guide](https://sites.psu.edu/symbolcodes/languages/psu/spanish/) for the different keystrokes needed to input that letter.  Once you know the necessary keystrokes, you can define a new ZMK macro in the "Custom Defined Behaviors" snippet and then bind it to your desired key in the Glove80 Layout Editor.  For example, see [this Glove80 keymap](https://my.glove80.com/#/layout/user/838002a9-9c13-4b85-aab7-e40d4be04b68
) for typing Swedish letters on macOS under the en-US locale, with [further discussion on Discord](https://discord.com/channels/877392805654306816/1156332285449220096) including screenshots and keymap variations for Norwegian letters.

**Comment by sunaku** [comment]
Alternatively, you could write a ZMK macro to temporarily instruct your computer to switch locale from en-US to es-ES, and then send the native keystrokes for Ñ, and finally switch back to en-US.  As before, this would all depend on your operating system.  For example, see the `uk_numbers1` and `uk_numbers2` macros in [this Glove80 keymap](https://my.glove80.com/#/layout/user/4561c4cb-54a7-4751-a27a-ee71cd646375) for inputting Danish letters.

**Comment by sunaku** [comment]
Hey @JavierOrtegaP, you should be able to do it through the `world.yaml` file now in v25. :tada:  See the instructions in the customization section of the README.
