### ISSUE TITLE
RGB support

### ISSUE THREAD

**Issue by skewty** [sunaku/glove80-keymaps#22]
Not sure how difficult it would be to merge in the RGB code with what is currently being used for this layout (with mouse cursor and ??? mods) and then get it onto the drop down on the MoErgo website but it is likely a huge quality of life improvement for most users.

One could match the key colors with what is printed in the PDF files.

https://my.glove80.com/#/search/?tags=rgb

"FuMo 68" from the search results list has a feature to optionally color the base layer (make a transparent layer one above base and toggle it on and off). This would be nice for dark room work where keyboards are plugged in to usb.

**Comment by sunaku** [comment]
I've partially implemented RGB indicators for layers and home row mods in commit 29a8a28bef8ef7fcc36c7fcd762fbc67405f80e0 using the PR30 beta firmware.

**Comment by sunaku** [comment]
Support for per-key RGB indicators (via PR30 beta firmware) has been [released in v39](https://github.com/sunaku/glove80-keymaps/releases/tag/v39).
